=== Oakflesh/MEAL-DATA/ModelProfileSchema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Model Profile Schema",
    "description": "JSON schema Model Profile object",
    "type": "object",
    "required": [
        "actions",
        "armies",
        "magic",
        "modelCount",
        "mounts",
        "name",
        "unique",
        "points",
        "race",
        "rules",
        "stats",
        "type",
        "wargear",
        "references",
        "version"
    ],
    "defaultSnippets": [
        {
            "label": "Default Hero",
            "body": {
                "Armies Of The Lord Of The Rings": {
                    "page": "$1",
                    "initials": "AotLotR"
                }
            }
        },
        {
            "label": "Default Warrior",
            "body": {
                "Armies Of The Lord Of The Rings": {
                    "page": "$1",
                    "initials": "AotLotR"
                }
            }
        }
    ],
    "properties": {
        "actions": {
            "type": "object",
            "additionalProperties": {
                "type": "object"
            }
        },
        "armies": {
            "type": "object",
            "additionalProperties": {
                "type": "object",
                "additionalProperties": {
                    "tier": {
                        "type": "string"
                    },
                    "selectableInWarband": {
                        "type": "boolean"
                    },
                    "warbandSize": {
                        "type": "integer"
                    }
                },
                "required": [
                    "tier",
                    "selectableInWarband",
                    "warbandSize"
                ]
            }
        },
        "magic": {
            "type": "object",
            "additionalProperties": {
                "type": "object"
            }
        },
        "modelCount": {
            "type": "integer"
        },
        "mounts": {
            "type": "object",
            "additionalProperties": {
                "type": "object",
                "additionalProperties": {
                    "points": {
                        "type": "integer"
                    },
                    "userSelected": {
                        "type": "boolean"
                    }
                },
                "required": [
                    "points",
                    "userSelected"
                ]
            }
        },
        "name": {
            "type": "string"
        },
        "unique": {
            "type": "boolean"
        },
        "uniqueName": {
            "type": "string"
        },
        "points": {
            "type": "integer"
        },
        "race": {
            "type": "object"
        },
        "rules": {
            "type": "object",
            "additionalProperties": {
                "type": "object",
                "properties": {
                    "type": {
                        "enum": [
                            "Active",
                            "Passive"
                        ]
                    }
                },
                "required": [
                    "type"
                ]
            }
        },
        "stats": {
            "type": "object",
            "additionalProperties": {
                "movement": {
                    "type": "integer"
                },
                "fight": {
                    "type": "integer"
                },
                "range": {
                    "type": "integer"
                },
                "strength": {
                    "type": "integer"
                },
                "defence": {
                    "type": "integer"
                },
                "attacks": {
                    "type": "integer"
                },
                "wounds": {
                    "type": "integer"
                },
                "courage": {
                    "type": "integer"
                },
                "might": {
                    "type": "object",
                    "additionalProperties": {
                        "additional": {
                            "type": "integer"
                        },
                        "points": {
                            "type": "integer"
                        },
                        "value": {
                            "type": "integer"
                        }
                    },
                    "required": [
                        "value"
                    ]
                },
                "will": {
                    "type": "object",
                    "additionalProperties": {
                        "additional": {
                            "type": "integer"
                        },
                        "points": {
                            "type": "integer"
                        },
                        "value": {
                            "type": "integer"
                        }
                    },
                    "required": [
                        "value"
                    ]
                },
                "fate": {
                    "type": "object",
                    "additionalProperties": {
                        "additional": {
                            "type": "integer"
                        },
                        "points": {
                            "type": "integer"
                        },
                        "value": {
                            "type": "integer"
                        }
                    },
                    "required": [
                        "value"
                    ]
                }
            },
            "required": [
                "movement",
                "fight",
                "range",
                "strength",
                "defence",
                "attacks",
                "wounds",
                "courage"
            ]
        },
        "type": {
            "type": "object"
        },
        "wargear": {
            "type": "object",
            "additionalProperties": {
                "type": "object",
                "properties": {
                    "optional": {
                        "type": "boolean"
                    },
                    "points": {
                        "type": "integer"
                    },
                    "type": {
                        "type": "string"
                    },
                    "userSelected": {
                        "type": "boolean"
                    },
                    "unique": {
                        "type": "boolean"
                    },
                    "asterisk": {
                        "type": "string"
                    }
                },
                "required": [
                    "optional",
                    "points",
                    "type",
                    "userSelected"
                ],
                "additionalProperties": false
            }
        },
        "references": {
            "type": "object",
            "books": {
                "type": "object",
                "additionalProperties": {
                    "type": "object",
                    "additionalProperties": {
                        "page": {
                            "type": "integer"
                        },
                        "initials": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "page",
                        "initials"
                    ]
                }
            }
        },
        "version": {
            "type": "number"
        }
    }
}

=== Oakflesh/MEAL-DATA/Model Profiles/Forces of Good/Lothlórien/Haldir.json
{
    "actions": {
        "Accuracy": {},
        "Strike": {},
        "Strength": {}
    },
    "armies": {
        "Lothlórien": {
            "tier": "Hero of Fortitude",
            "selectableInWarband": false,
            "warbandSize": 12
        }
    },
    "magic": {},
    "modelCount": 1,
    "mounts": {},
    "name": "Haldir",
    "unique": true,
    "uniqueName": "Haldir",
    "points": 70,
    "race": {
        "Elf": {},
        "Lόrien": {}
    },
    "rules": {
        "Expert Shot": {
            "type": "Passive"
        },
        "Woodland Creature": {
            "type": "Passive"
        },
        "Allies 'Til The End": {
            "type": "Passive"
        },
        "One Final Blow": {
            "type": "Active"
        }
    },
    "stats": {
        "movement": 6,
        "fight": 6,
        "range": 3,
        "strength": 4,
        "defence": 4,
        "attacks": 2,
        "wounds": 2,
        "courage": 6,
        "might": {
            "additional": 0,
            "points": 0,
            "value": 3
        },
        "will": {
            "additional": 0,
            "points": 0,
            "value": 1
        },
        "fate": {
            "additional": 0,
            "points": 0,
            "value": 1
        }
    },
    "type": {
        "Infantry": {}
    },
    "wargear": {
        "Elven-Made Hand-And-A-Half Sword": {
            "optional": false,
            "points": 0,
            "type": "Passive",
            "userSelected": false
        },
        "Heavy Armour": {
            "optional": true,
            "points": 10,
            "type": "Passive",
            "userSelected": false
        },
        "Elf Bow": {
            "optional": true,
            "points": 5,
            "type": "Passive",
            "userSelected": false
        },
        "Elven Cloak": {
            "optional": true,
            "points": 5,
            "type": "Passive",
            "userSelected": false
        }
    },
    "references": {
        "books": {
            "Armies Of The Lord Of The Rings": {
                "page": 85,
                "initials": "AotLotR"
            }
        }
    },
    "version": 1.0
}

=== Oakflesh/MEAL-DATA/Model Profiles/Good/Minas Tirith/Knight Of Minas Tirith.json
{
    "actions": {},
    "armies": {
        "Minas Tirith": {
            "tier": "Warrior",
            "selectableInWarband": true,
            "warbandSize": 0
        }
    },
    "magic": {},
    "modelCount": 1,
    "mounts": {
        "Horse":{
            "optional": false,
            "points": 0,
            "userSelected": true
        }
    },
    "name": "Knight Of Minas Tirith",
    "unique": false,
    "points": 13,
    "race": {
        "Man": {},
        "Gondor": {}
    },
    "rules": {
        "Shieldwall": {
            "type": "Passive"
        }
    },
    "stats": {
        "movement": 6,
        "fight": 3,
        "range": 4,
        "strength": 3,
        "defence": 5,
        "attacks": 1,
        "wounds": 1,
        "courage": 3
    },
    "type": {
        "Cavalry": {}
    },
    "wargear": {
        "Heavy Armour": {
            "optional": false,
            "points": 0,
            "type": "Passive",
            "userSelected": false
        },
        "Sword": {
            "optional": false,
            "points": 0,
            "type": "Passive",
            "userSelected": false
        },
        "Lance": {
            "optional": false,
            "points": 0,
            "type": "Passive",
            "userSelected": false
        },
        "Banner": {
            "optional": true,
            "points": 25,
            "type": "Passive",
            "userSelected": false
        },
        "Shield": {
            "optional": true,
            "points": 1,
            "type": "Passive",
            "userSelected": false
        }
    },
    "references": {
        "books": {
            "Armies Of The Lord Of The Rings": {
                "page": 41,
                "initials": "AotLotR"
            }
        }
    },
    "version": 1.0
}

=== Oakflesh/MEAL-DATA/Model Profiles/Good/Lothlόrien/Galadhrim Stormcaller.json
{
    "actions": {
        "Channelling": {}
    },
    "armies": {
        "Lothlórien": {
            "tier": "Minor Hero",
            "selectableInWarband": false,
            "warbandSize": 6
        }
    },
    "magic": {
        "Call Winds": {
            "range": 12,
            "casting": 3
        },
        "Enchanted Blades": {
            "range": 6,
            "casting": 4
        }
    },
    "modelCount": 1,
    "mounts": {},
    "name": "Galadhrim Stormcaller",
    "unique": false,
    "points": 60,
    "race": {
        "Elf": {},
        "Lόrien": {}
    },
    "rules": {
        "Woodland Creature": {
            "type": "Passive"
        },
        "Powers Of Nature": {
            "type": "Active"
        }
    },
    "stats": {
        "movement": 6,
        "fight": 5,
        "range": 3,
        "strength": 3,
        "defence": 4,
        "attacks": 1,
        "wounds": 2,
        "courage": 5,
        "might": {
            "additional": 0,
            "points": 0,
            "value": 1
        },
        "will": {
            "additional": 0,
            "points": 0,
            "value": 3
        },
        "fate": {
            "additional": 0,
            "points": 0,
            "value": 1
        }
    },
    "type": {
        "Infantry": {}
    },
    "wargear": {
        "Armour": {
            "optional": false,
            "points": 0,
            "type": "Passive",
            "userSelected": false
        },
        "Elven-Made Sword": {
            "optional": false,
            "points": 0,
            "type": "Passive",
            "userSelected": false
        },
        "Staff": {
            "optional": false,
            "points": 0,
            "type": "Passive",
            "userSelected": false
        }
    },
    "references": {
        "books": {
            "Armies Of The Lord Of The Rings": {
                "page": 86,
                "initials": "AotLotR"
            }
        }
    },
    "version": 1.0
}

=== Oakflesh/MEAL-DATA/Model Profiles/Forces of Good/The Fiefdoms/Price Imrahil Of Dol Amroth.json
{
    "actions": {
        "Resolve": {},
        "Strike": {},
        "Strength": {},
        "Defence": {}
    },
    "armies": {
        "The Fiefdoms": {
            "tier": "Hero of Legend",
            "selectableInWarband": false,
            "warbandSize": 18
        }
    },
    "magic": {},
    "modelCount": 1,
    "mounts": {
        "Armoured Horse": {
            "points": 15,
            "userSelected": false
        }
    },
    "name": "Price Imrahil Of Dol Amroth",
    "unique": true,
    "uniqueName": "Price Imrahil Of Dol Amroth",
    "points": 140,
    "race": {
        "Man": {},
        "Gondor": {}
    },
    "rules": {
        "The Lineage Of NÃºmenor": {
            "type": "Active"
        },
        "Dol Amroth For Gondor!": {
            "type": "Passive",
            "asterisk": "*"
        }
    },
    "stats": {
        "movement": 6,
        "fight": 6,
        "range": 4,
        "strength": 4,
        "defence": 7,
        "attacks": 3,
        "wounds": 3,
        "courage": 6,
        "might": {
            "current": 3
        },
        "will": {
            "current": 3
        },
        "fate": {
            "current": 3
        }
    },
    "type": {
        "Infantry": {}
    },
    "wargear": {
        "Heavy Armour": {
            "optional": false,
            "points": 0,
            "type": "Passive",
            "userSelected": false
        },
        "Sword": {
            "optional": false,
            "points": 0,
            "type": "Passive",
            "userSelected": false
        },
        "Shield": {
            "optional": false,
            "points": 0,
            "type": "Passive",
            "userSelected": false
        },
        "Lance": {
            "optional": true,
            "points": 5,
            "type": "Passive",
            "userSelected": false
        }
    },
    "references": {
        "books": {
            "Armies Of The Lord Of The Rings": {
                "page": 47,
                "initials": "AotLotR"
            }
        }
    },
    "version": 1.0
}

=== Oakflesh/MEAL-DATA/Model Profiles/Good/The Shire/Bilbo Baggins.json
{
    "actions": {
        "Resolve": {}
    },
    "armies": {
        "The Shire": {
            "tier": "Hero Of Fortitude",
            "selectableInWarband": false,
            "warbandSize": 12
        }
    },
    "magic": {},
    "modelCount": 1,
    "mounts": {},
    "name": "Bilbo Baggins",
    "unique": true,
    "uniqueName": "Bilbo",
    "points": 40,
    "race": {
        "Hobbit": {}
    },
    "rules": {
        "Resistant To Magic": {
            "type": "Passive"
        },
        "Throw Stones (Hobbit)": {
            "type": "Active"
        }
    },
    "stats": {
        "movement": 4,
        "fight": 3,
        "range": 3,
        "strength": 2,
        "defence": 2,
        "attacks": 1,
        "wounds": 2,
        "courage": 6,
        "might": {
            "additional": 0,
            "points": 0,
            "value": 1
        },
        "will": {
            "additional": 0,
            "points": 0,
            "value": 3
        },
        "fate": {
            "additional": 0,
            "points": 0,
            "value": 3
        }
    },
    "type": {
        "Infantry": {}
    },
    "wargear": {
        "Dagger": {
            "optional": false,
            "points": 0,
            "type": "Passive",
            "userSelected": false
        },
        "The One Ring": {
            "optional": true,
            "points": 0,
            "type": "Passive",
            "userSelected": false,
            "unique": true
        },
        "Mithril Coat": {
            "optional": true,
            "points": 15,
            "type": "Passive",
            "userSelected": false,
            "unique": true
        },
        "Sting": {
            "optional": true,
            "points": 5,
            "type": "Passive",
            "userSelected": false,
            "unique": true
        }
    },
    "references": {
        "books": {
            "Armies Of The Lord Of The Rings": {
                "page": 21,
                "initials": "AotLotR"
            }
        }
    },
    "version": 1.0
}

=== Oakflesh/MEAL-DATA/Model Profiles/Good/Númenor/Elendil, High King Of Gondor And Arnor.json
{
    "actions": {
        "Strike": {},
        "Strength": {},
        "Defence": {},
        "Challenge": {}
    },
    "armies": {
        "Númenor": {
            "tier": "Hero Of Legend",
            "selectableInWarband": false,
            "warbandSize": 18
        }
    },
    "magic": {},
    "modelCount": 1,
    "mounts": {
        "Horse": {
            "points": 10,
            "userSelected": false
        }
    },
    "name": "Elendil, High King Of Gondor And Arnor",
    "unique": true,
    "uniqueName": "Elendil, High King Of Gondor And Arnor",
    "points": 185,
    "race": {
        "Man": {},
        "Númenor": {}
    },
    "rules": {
        "High King Of Gondor And Arnor": {
            "type": "Active"
        },
        "Unbending Resolve": {
            "type": "Passive"
        }
    },
    "stats": {
        "movement": 6,
        "fight": 7,
        "range": 4,
        "strength": 5,
        "defence": 7,
        "attacks": 3,
        "wounds": 3,
        "courage": 6,
        "might": {
            "additional": 0,
            "points": 0,
            "value": 3
        },
        "will": {
            "additional": 0,
            "points": 0,
            "value": 3
        },
        "fate": {
            "additional": 0,
            "points": 0,
            "value": 1
        }
    },
    "type": {
        "Infantry": {}
    },
    "wargear": {
        "Narsil": {
            "optional": false,
            "points": 0,
            "type": "Passive",
            "userSelected": false
        },
        "Heavy Armour": {
            "optional": false,
            "points": 0,
            "type": "Passive",
            "userSelected": false
        },
        "Shield": {
            "optional": true,
            "points": 5,
            "type": "Passive",
            "userSelected": false
        }
    },
    "references": {
        "books": {
            "Armies Of The Lord Of The Rings": {
                "page": 29,
                "initials": "AotLotR"
            }
        }
    },
    "version": 1.0
}

=== Oakflesh/MEAL-DATA/Model Profiles/Good/Minas Tirith/Beregond, Guard Of The Citadel.json
{
    "actions": {
        "Accuracy": {}
    },
    "armies": {
        "Minas Tirith": {
            "tier": "Minor Hero",
            "selectableInWarband": false,
            "warbandSize": 6
        }
    },
    "magic": {},
    "modelCount": 1,
    "mounts": {
        "Horse": {
            "points": 5,
            "userSelected": false
        }
    },
    "name": "Beregond, Guard Of The Citadel",
    "unique": true,
    "uniqueName": "Beregond",
    "points": 30,
    "race": {
        "Man": {},
        "Gondor": {}
    },
    "rules": {
        "Bodyguard":{
            "type":"Passive"
        }
    },
    "stats": {
        "movement": 6,
        "fight": 4,
        "range": 3,
        "strength": 4,
        "defence": 6,
        "attacks": 1,
        "wounds": 1,
        "courage": 4,
        "might": {
            "additional": 0,
            "points": 0,
            "value": 1
        },
        "will": {
            "additional": 0,
            "points": 0,
            "value": 1
        },
        "fate": {
            "additional": 0,
            "points": 0,
            "value": 1
        }
    },
    "type": {
        "Infantry": {}
    },
    "wargear": {
        "Heavy Armour": {
            "optional": false,
            "points": 0,
            "type": "Passive",
            "userSelected": false
        },
        "Sword": {
            "optional": false,
            "points": 0,
            "type": "Passive",
            "userSelected": false
        },
        "Longbow": {
            "optional": false,
            "points": 0,
            "type": "Passive",
            "userSelected": false
        }
    },
    "references": {
        "books": {
            "Armies Of The Lord Of The Rings": {
                "page": 37,
                "initials": "AotLotR"
            }
        }
    },
    "version": 1.0
}

=== Oakflesh/MEAL-DATA/Model Profiles/Forces of Good/The Shire/Fredegar Bolger.json
{
    "actions": {},
    "armies": {
        "The Shire": {
            "tier": "Minor Hero",
            "selectableInWarband": false,
            "warbandSize": 6
        }
    },
    "magic": {},
    "modelCount": 1,
    "mounts": {},
    "name": "Fredegar Bolger",
    "unique": true,
    "uniqueName": "Fredegar Bolger",
    "points": 10,
    "race": {
        "Hobbit": {}
    },
    "rules": {
        "Resistant To Magic": {
            "type": "Passive"
        },
        "Throw Stones (Hobbit)": {
            "type": "Active"
        }
    },
    "stats": {
        "movement": 4,
        "fight": 2,
        "range": 3,
        "strength": 2,
        "defence": 3,
        "attacks": 1,
        "wounds": 1,
        "courage": 3,
        "might": {
            "current": 0
        },
        "will": {
            "current": 0
        },
        "fate": {
            "current": 1
        }
    },
    "type": {
        "Infantry": {}
    },
    "wargear": {
        "Unarmed": {
            "optional": false,
            "points": 0,
            "type": "Passive",
            "userSelected": false
        }
    },
    "references": {
        "books": {
            "Armies Of The Lord Of The Rings": {
                "page": 20,
                "initials": "AotLotR"
            }
        }
    },
    "version": 1.0
}
