=== Oakflesh/MEAL-DATA/ModelProfileSchema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Model Profile Schema",
    "description": "JSON schema Model Profile object",
    "type": "object",
    "required": [
        "actions",
        "armies",
        "magic",
        "modelCount",
        "mounts",
        "name",
        "unique",
        "points",
        "race",
        "rules",
        "stats",
        "type",
        "wargear",
        "references",
        "version"
    ],
    "defaultSnippets": [
        {
            "label": "Default Hero",
            "body": {
                "Armies Of The Lord Of The Rings": {
                    "page": "$1",
                    "initials": "AotLotR"
                }
            }
        },
        {
            "label": "Default Warrior",
            "body": {
                "Armies Of The Lord Of The Rings": {
                    "page": "$1",
                    "initials": "AotLotR"
                }
            }
        }
    ],
    "properties": {
        "actions": {
            "type": "object",
            "additionalProperties": {
                "type": "object"
            }
        },
        "armies": {
            "type": "object",
            "additionalProperties": {
                "type": "object",
                "additionalProperties": {
                    "tier": {
                        "type": "string"
                    },
                    "selectableInWarband": {
                        "type": "boolean"
                    },
                    "warbandSize": {
                        "type": "integer"
                    }
                },
                "required": [
                    "tier",
                    "selectableInWarband",
                    "warbandSize"
                ]
            }
        },
        "magic": {
            "type": "object",
            "additionalProperties": {
                "type": "object"
            }
        },
        "modelCount": {
            "type": "integer"
        },
        "mounts": {
            "type": "object",
            "additionalProperties": {
                "type": "object",
                "additionalProperties": {
                    "points": {
                        "type": "integer"
                    },
                    "userSelected": {
                        "type": "boolean"
                    }
                },
                "required": [
                    "points",
                    "userSelected"
                ]
            }
        },
        "name": {
            "type": "string"
        },
        "unique": {
            "type": "boolean"
        },
        "uniqueName": {
            "type": "string"
        },
        "points": {
            "type": "integer"
        },
        "race": {
            "type": "object"
        },
        "rules": {
            "type": "object",
            "additionalProperties": {
                "type": "object",
                "properties": {
                    "type": {
                        "enum": [
                            "Active",
                            "Passive"
                        ]
                    }
                },
                "required": [
                    "type"
                ]
            }
        },
        "stats": {
            "type": "object",
            "additionalProperties": {
                "movement": {
                    "type": "integer"
                },
                "fight": {
                    "type": "integer"
                },
                "range": {
                    "type": "integer"
                },
                "strength": {
                    "type": "integer"
                },
                "defence": {
                    "type": "integer"
                },
                "attacks": {
                    "type": "integer"
                },
                "wounds": {
                    "type": "integer"
                },
                "courage": {
                    "type": "integer"
                },
                "might": {
                    "type": "object",
                    "additionalProperties": {
                        "additional": {
                            "type": "integer"
                        },
                        "points": {
                            "type": "integer"
                        },
                        "value": {
                            "type": "integer"
                        }
                    },
                    "required": [
                        "value"
                    ]
                },
                "will": {
                    "type": "object",
                    "additionalProperties": {
                        "additional": {
                            "type": "integer"
                        },
                        "points": {
                            "type": "integer"
                        },
                        "value": {
                            "type": "integer"
                        }
                    },
                    "required": [
                        "value"
                    ]
                },
                "fate": {
                    "type": "object",
                    "additionalProperties": {
                        "additional": {
                            "type": "integer"
                        },
                        "points": {
                            "type": "integer"
                        },
                        "value": {
                            "type": "integer"
                        }
                    },
                    "required": [
                        "value"
                    ]
                }
            },
            "required": [
                "movement",
                "fight",
                "range",
                "strength",
                "defence",
                "attacks",
                "wounds",
                "courage"
            ]
        },
        "type": {
            "type": "object"
        },
        "wargear": {
            "type": "object",
            "additionalProperties": {
                "type": "object",
                "properties": {
                    "optional": {
                        "type": "boolean"
                    },
                    "points": {
                        "type": "integer"
                    },
                    "type": {
                        "type": "string"
                    },
                    "userSelected": {
                        "type": "boolean"
                    },
                    "unique": {
                        "type": "boolean"
                    },
                    "asterisk": {
                        "type": "string"
                    }
                },
                "required": [
                    "optional",
                    "points",
                    "type",
                    "userSelected"
                ],
                "additionalProperties": false
            }
        },
        "references": {
            "type": "object",
            "books": {
                "type": "object",
                "additionalProperties": {
                    "type": "object",
                    "additionalProperties": {
                        "page": {
                            "type": "integer"
                        },
                        "initials": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "page",
                        "initials"
                    ]
                }
            }
        },
        "version": {
            "type": "number"
        }
    }
}

=== Oakflesh/MEAL-DATA/Model Profiles/Good/Rohan/Grimbold Of Grimslade.json
{
    "actions": {
        "Strength": {}
    },
    "armies": {
        "Rohan": {
            "tier": "Hero ofFortitude",
            "selectableInWarband": false,
            "warbandSize": 12
        }
    },
    "magic": {},
    "modelCount": 1,
    "mounts": {},
    "name": "Grimbold Of Grimslade",
    "unique": true,
    "uniqueName": "Grimbold Of Grimslade",
    "points": 60,
    "race": {
        "Man": {},
        "Rohan": {}
    },
    "rules": {
        "Might Blow": {
            "type": "Passive"
        }
    },
    "stats": {
        "movement": 6,
        "fight": 5,
        "range": 4,
        "strength": 4,
        "defence": 5,
        "attacks": 2,
        "wounds": 2,
        "courage": 4,
        "might": {
            "additional": 0,
            "points": 0,
            "value": 3
        },
        "will": {
            "additional": 0,
            "points": 0,
            "value": 1
        },
        "fate": {
            "additional": 0,
            "points": 0,
            "value": 1
        }
    },
    "type": {
        "Infantry": {}
    },
    "wargear": {
        "Armour": {
            "optional": false,
            "points": 0,
            "type": "Passive",
            "userSelected": false
        },
        "Two-Handed Axe": {
            "optional": false,
            "points": 0,
            "type": "Passive",
            "userSelected": false
        }
    },
    "references": {
        "books": {
            "Armies Of The Lord Of The Rings": {
                "page": 65,
                "initials": "AotLotR"
            }
        }
    },
    "version": 1.0
}

=== Oakflesh/MEAL-DATA/Model Profiles/Good/The Fiefdoms/Angbor The Fearless.json
{
    "actions": {
        "Strike": {}
    },
    "armies": {
        "The Fiefdoms": {
            "tier": "Hero ofValour",
            "selectableInWarband": false,
            "warbandSize": 15
        }
    },
    "magic": {},
    "modelCount": 1,
    "mounts": {},
    "name": "Angbor The Fearless",
    "unique": true,
    "uniqueName": "Angbor The Fearless",
    "points": 65,
    "race": {
        "Man": {},
        "Gondor": {}
    },
    "rules": {
        "Chief Of Lamedon": {
            "type": "Passive",
            "asterisk": "*"
        },
        "Fearless": {
            "type": "Passive"
        }
    },
    "stats": {
        "movement": 6,
        "fight": 5,
        "range": 4,
        "strength": 4,
        "defence": 5,
        "attacks": 2,
        "wounds": 2,
        "courage": 5,
        "might": {
            "additional": 0,
            "points": 0,
            "value": 2
        },
        "will": {
            "additional": 0,
            "points": 0,
            "value": 3
        },
        "fate": {
            "additional": 0,
            "points": 0,
            "value": 1
        }
    },
    "type": {
        "Infantry": {}
    },
    "wargear": {
        "Armour": {
            "optional": false,
            "points": 0,
            "type": "Passive",
            "userSelected": false
        },
        "Broadsword": {
            "optional": false,
            "points": 0,
            "type": "Passive",
            "userSelected": false
        }
    },
    "references": {
        "books": {
            "Armies Of The Lord Of The Rings": {
                "page": 48,
                "initials": "AotLotR"
            }
        }
    },
    "version": 1.0
}

=== Oakflesh/MEAL-DATA/Model Profiles/Forces of Good/The Shire/Samwise The Brave.json
{
    "actions": {
        "Strike": {},
        "Resolve": {}
    },
    "armies": {
        "The Shire": {
            "tier": "Hero of Fortitude",
            "selectableInWarband": false,
            "warbandSize": 12
        }
    },
    "magic": {},
    "modelCount": 1,
    "mounts": {
        "Pony": {
            "points": 5,
            "userSelected": false
        }
    },
    "name": "Samwise The Brave",
    "unique": true,
    "uniqueName": "Samwise",
    "points": 45,
    "race": {
        "Hobbit": {}
    },
    "rules": {
        "Resistant To Magic": {
            "type": "Passive"
        },
        "Throw Stones (Hobbit)": {
            "type": "Active"
        }
    },
    "stats": {
        "movement": 4,
        "fight": 3,
        "range": 3,
        "strength": 2,
        "defence": 3,
        "attacks": 1,
        "wounds": 2,
        "courage": 6,
        "might": {
            "additional": 0,
            "points": 0,
            "value": 2
        },
        "will": {
            "additional": 0,
            "points": 0,
            "value": 2
        },
        "fate": {
            "additional": 0,
            "points": 0,
            "value": 3
        }
    },
    "type": {
        "Infantry": {}
    },
    "wargear": {
        "Elven Cloak": {
            "optional": true,
            "points": 5,
            "type": "Passive",
            "userSelected": false
        },
        "Sting": {
            "optional": false,
            "points": 0,
            "type": "Passive",
            "userSelected": true,
            "unique": true
        }
    },
    "references": {
        "books": {
            "Armies Of The Lord Of The Rings": {
                "page": 17,
                "initials": "AotLotR"
            }
        }
    },
    "version": 1.0
}

=== Oakflesh/MEAL-DATA/Model Profiles/Good/Rohan/Háma, Captain Of Rohan.json
{
    "actions": {
        "Defence": {}
    },
    "armies": {
        "Rohan": {
            "tier": "Hero Of Fortitude",
            "selectableInWarband": false,
            "warbandSize": 12
        }
    },
    "magic": {},
    "modelCount": 1,
    "mounts": {
        "Horse": {
            "points": 10,
            "userSelected": false
        }
    },
    "name": "Háma, Captain Of Rohan",
    "unique": true,
    "uniqueName": "Háma",
    "points": 55,
    "race": {
        "Man": {},
        "Rohan": {}
    },
    "rules": {
        "Expert Rider": {
            "type": "Passive"
        },
        "Horse Lord": {
            "type": "Passive"
        },
        "Sworn Protector": {
            "type": "Passive",
            "additional": "Théoden"
        }
    },
    "stats": {
        "movement": 6,
        "fight": 4,
        "range": 4,
        "strength": 4,
        "defence": 6,
        "attacks": 2,
        "wounds": 2,
        "courage": 4,
        "might": {
            "additional": 0,
            "points": 0,
            "value": 3
        },
        "will": {
            "additional": 0,
            "points": 0,
            "value": 1
        },
        "fate": {
            "additional": 0,
            "points": 0,
            "value": 1
        }
    },
    "type": {
        "Infantry": {}
    },
    "wargear": {
        "Heavy Armour": {
            "optional": false,
            "points": 0,
            "type": "Passive",
            "userSelected": false
        },
        "Sword": {
            "optional": false,
            "points": 0,
            "type": "Passive",
            "userSelected": false
        }
    },
    "references": {
        "books": {
            "Armies Of The Lord Of The Rings": {
                "page": 65,
                "initials": "AotLotR"
            }
        }
    },
    "version": 1.0
}

=== Oakflesh/MEAL-DATA/Model Profiles/Good/The Kingdom Of Khazad-Dûm/Flói Stonehand.json
{
    "actions": {
        "Strength": {}
    },
    "armies": {
        "The Kingdom Of Khazad-Dûm": {
            "tier": "Hero Of Fortitude",
            "selectableInWarband": false,
            "warbandSize": 12
        }
    },
    "magic": {},
    "modelCount": 1,
    "mounts": {},
    "name": "Flói Stonehand",
    "unique": true,
    "uniqueName": "Flói Stonehand",
    "points": 75,
    "race": {
        "Dwarf": {},
        "Moria": {}
    },
    "rules": {
        "Loremaster": {
            "type": "Active"
        }
    },
    "stats": {
        "movement": 5,
        "fight": 4,
        "range": 4,
        "strength": 4,
        "defence": 6,
        "attacks": 2,
        "wounds": 2,
        "courage": 5,
        "might": {
            "additional": 0,
            "points": 0,
            "value": 1
        },
        "will": {
            "additional": 0,
            "points": 0,
            "value": 3
        },
        "fate": {
            "additional": 0,
            "points": 0,
            "value": 1
        }
    },
    "type": {
        "Infantry": {}
    },
    "wargear": {
        "Heavy Dwarf Armour": {
            "optional": false,
            "points": 0,
            "type": "Passive",
            "userSelected": false
        },
        "Staff": {
            "optional": false,
            "points": 0,
            "type": "Active",
            "userSelected": false
        }
    },
    "references": {
        "books": {
            "Armies Of The Lord Of The Rings": {
                "page": 98,
                "initials": "AotLotR"
            }
        }
    },
    "version": 1.0
}

=== Oakflesh/MEAL-DATA/Model Profiles/Good/The Misty Mountains/Great Eagle.json
{
    "actions": {},
    "armies": {
        "The Misty Mountain": {
            "tier": "Warrior",
            "selectableInWarband": true,
            "warbandSize": 0
        }
    },
    "magic": {},
    "modelCount": 1,
    "mounts": {},
    "name": "Great Eagle",
    "unique": false,
    "points": 100,
    "race": {
        "Eagle": {}
    },
    "rules": {
        "Terror": {
            "type": "Passive"
        },
        "Fly": {
            "type": "Passive"
        },
        "Monstrous Charge": {
            "type": "Active"
        }
    },
    "stats": {
        "movement": 3,
        "fight": 7,
        "range": 4,
        "strength": 6,
        "defence": 8,
        "attacks": 2,
        "wounds": 3,
        "courage": 6
    },
    "type": {
        "Monster": {},
        "Infantry": {}
    },
    "wargear": {
        "Claws & Beak": {
            "optional": false,
            "points": 0,
            "type": "Passive",
            "userSelected": false
        }
    },
    "references": {
        "books": {
            "Armies Of The Lord Of The Rings": {
                "page": 95,
                "initials": "AotLotR"
            }
        }
    },
    "version": 1
}

=== Oakflesh/MEAL-DATA/Model Profiles/Forces of Good/Rivendell/Círdan.json
{
    "actions": {
        "Channelling": {},
        "Resolve": {}
    },
    "armies": {
        "Rivendell": {
            "tier": "Hero of Fortitude",
            "selectableInWarband": false,
            "warbandSize": 12
        }
    },
    "magic": {
        "Aura Of Command": {
            "range": 0,
            "casting": 2
        },
        "Blinding Light": {
            "range": 0,
            "casting": 2
        },
        "Enchanted Blades": {
            "range": 6,
            "casting": 4
        },
        "Aura Of Dismay": {
            "range": 0,
            "casting": 5
        }
    },
    "modelCount": 1,
    "mounts": {},
    "name": "Círdan",
    "unique": true,
    "uniqueName": "Círdan",
    "points": 80,
    "race": {
        "Elf": {},
        "Rivendell": {}
    },
    "rules": {
        "Resistant To Magic": {
            "type": "Passive"
        },
        "Woodland Creature": {
            "type": "Passive"
        },
        "Terror": {
            "type": "Passive"
        },
        "The Shipwright's Power": {
            "type": "Passive",
            "asterisk": "*"
        }
    },
    "stats": {
        "movement": 6,
        "fight": 5,
        "range": 3,
        "strength": 4,
        "defence": 4,
        "attacks": 1,
        "wounds": 2,
        "courage": 6,
        "might": {
            "additional": 0,
            "points": 0,
            "value": 1
        },
        "will": {
            "additional": 0,
            "points": 0,
            "value": 4,
            "asterisk": "*"
        },
        "fate": {
            "additional": 0,
            "points": 0,
            "value": 1
        }
    },
    "type": {
        "Infantry": {}
    },
    "wargear": {
        "Unarmed": {
            "optional": false,
            "points": 0,
            "type": "Passive",
            "userSelected": false
        }
    },
    "references": {
        "books": {
            "Armies Of The Lord Of The Rings": {
                "page": 78,
                "initials": "AotLotR"
            }
        }
    },
    "version": 1.0
}

=== Oakflesh/MEAL-DATA/Model Profiles/Forces of Good/Minas Tirith/Boromir, Captain Of The White Tower.json
{
    "actions": {
        "Strike": {},
        "Strength": {},
        "Defence": {}
    },
    "armies": {
        "Minas Tirith": {
            "tier": "Hero of Valour",
            "selectableInWarband": false,
            "warbandSize": 15
        }
    },
    "magic": {},
    "modelCount": 1,
    "mounts": {
        "Horse": {
            "points": 10,
            "userSelected": false
        }
    },
    "name": "Boromir, Captain Of The White Tower",
    "unique": true,
    "uniqueName": "Boromir",
    "points": 160,
    "race": {
        "Man": {},
        "Gondor": {}
    },
    "rules": {},
    "stats": {
        "movement": 6,
        "fight": 6,
        "range": 4,
        "strength": 4,
        "defence": 6,
        "attacks": 3,
        "wounds": 3,
        "courage": 6,
        "might": {
            "additional": 0,
            "points": 0,
            "value": 6
        },
        "will": {
            "additional": 0,
            "points": 0,
            "value": 3
        },
        "fate": {
            "additional": 0,
            "points": 0,
            "value": 3
        }
    },
    "type": {
        "Infantry": {}
    },
    "wargear": {
        "Sword": {
            "optional": false,
            "points": 0,
            "type": "Passive",
            "userSelected": false
        },
        "Heavy Armour": {
            "optional": false,
            "points": 0,
            "type": "Passive",
            "userSelected": false
        },
        "Horn Of Gondor": {
            "optional": false,
            "points": 0,
            "type": "Passive",
            "userSelected": false
        },
        "Banner of Minas Tirith": {
            "optional": true,
            "points": 40,
            "type": "Passive",
            "userSelected": false
        },
        "Lance": {
            "optional": true,
            "points": 5,
            "type": "Passive",
            "userSelected": false
        },
        "Shield": {
            "optional": true,
            "points": 5,
            "type": "Passive",
            "userSelected": false
        }
    },
    "references": {
        "books": {
            "Armies Of The Lord Of The Rings": {
                "page": 36,
                "initials": "AotLotR"
            }
        }
    },
    "version": 1.0
}
