=== Oakflesh/MEAL-DATA/ModelProfileSchema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Model Profile Schema",
    "description": "JSON schema Model Profile object",
    "type": "object",
    "required": [
        "actions",
        "armies",
        "magic",
        "modelCount",
        "mounts",
        "name",
        "unique",
        "points",
        "race",
        "rules",
        "stats",
        "type",
        "wargear",
        "references",
        "version"
    ],
    "defaultSnippets": [
        {
            "label": "Default Hero",
            "body": {
                "Armies Of The Lord Of The Rings": {
                    "page": "$1",
                    "initials": "AotLotR"
                }
            }
        },
        {
            "label": "Default Warrior",
            "body": {
                "Armies Of The Lord Of The Rings": {
                    "page": "$1",
                    "initials": "AotLotR"
                }
            }
        }
    ],
    "properties": {
        "actions": {
            "type": "object",
            "additionalProperties": {
                "type": "object"
            }
        },
        "armies": {
            "type": "object",
            "additionalProperties": {
                "type": "object",
                "additionalProperties": {
                    "tier": {
                        "type": "string"
                    },
                    "selectableInWarband": {
                        "type": "boolean"
                    },
                    "warbandSize": {
                        "type": "integer"
                    }
                },
                "required": [
                    "tier",
                    "selectableInWarband",
                    "warbandSize"
                ]
            }
        },
        "magic": {
            "type": "object",
            "additionalProperties": {
                "type": "object"
            }
        },
        "modelCount": {
            "type": "integer"
        },
        "mounts": {
            "type": "object",
            "additionalProperties": {
                "type": "object",
                "additionalProperties": {
                    "points": {
                        "type": "integer"
                    },
                    "userSelected": {
                        "type": "boolean"
                    }
                },
                "required": [
                    "points",
                    "userSelected"
                ]
            }
        },
        "name": {
            "type": "string"
        },
        "unique": {
            "type": "boolean"
        },
        "uniqueName": {
            "type": "string"
        },
        "points": {
            "type": "integer"
        },
        "race": {
            "type": "object"
        },
        "rules": {
            "type": "object",
            "additionalProperties": {
                "type": "object",
                "properties": {
                    "type": {
                        "enum": [
                            "Active",
                            "Passive"
                        ]
                    }
                },
                "required": [
                    "type"
                ]
            }
        },
        "stats": {
            "type": "object",
            "additionalProperties": {
                "movement": {
                    "type": "integer"
                },
                "fight": {
                    "type": "integer"
                },
                "range": {
                    "type": "integer"
                },
                "strength": {
                    "type": "integer"
                },
                "defence": {
                    "type": "integer"
                },
                "attacks": {
                    "type": "integer"
                },
                "wounds": {
                    "type": "integer"
                },
                "courage": {
                    "type": "integer"
                },
                "might": {
                    "type": "object",
                    "additionalProperties": {
                        "additional": {
                            "type": "integer"
                        },
                        "points": {
                            "type": "integer"
                        },
                        "value": {
                            "type": "integer"
                        }
                    },
                    "required": [
                        "value"
                    ]
                },
                "will": {
                    "type": "object",
                    "additionalProperties": {
                        "additional": {
                            "type": "integer"
                        },
                        "points": {
                            "type": "integer"
                        },
                        "value": {
                            "type": "integer"
                        }
                    },
                    "required": [
                        "value"
                    ]
                },
                "fate": {
                    "type": "object",
                    "additionalProperties": {
                        "additional": {
                            "type": "integer"
                        },
                        "points": {
                            "type": "integer"
                        },
                        "value": {
                            "type": "integer"
                        }
                    },
                    "required": [
                        "value"
                    ]
                }
            },
            "required": [
                "movement",
                "fight",
                "range",
                "strength",
                "defence",
                "attacks",
                "wounds",
                "courage"
            ]
        },
        "type": {
            "type": "object"
        },
        "wargear": {
            "type": "object",
            "additionalProperties": {
                "type": "object",
                "properties": {
                    "optional": {
                        "type": "boolean"
                    },
                    "points": {
                        "type": "integer"
                    },
                    "type": {
                        "type": "string"
                    },
                    "userSelected": {
                        "type": "boolean"
                    },
                    "unique": {
                        "type": "boolean"
                    },
                    "asterisk": {
                        "type": "string"
                    }
                },
                "required": [
                    "optional",
                    "points",
                    "type",
                    "userSelected"
                ],
                "additionalProperties": false
            }
        },
        "references": {
            "type": "object",
            "books": {
                "type": "object",
                "additionalProperties": {
                    "type": "object",
                    "additionalProperties": {
                        "page": {
                            "type": "integer"
                        },
                        "initials": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "page",
                        "initials"
                    ]
                }
            }
        },
        "version": {
            "type": "number"
        }
    }
}

=== Oakflesh/MEAL-DATA/Model Profiles/Forces of Good/Lothlórien/Rúmil.json
{
    "actions": {
        "Defence": {}
    },
    "armies": {
        "Lothlórien": {
            "tier": "Hero of Fortitude",
            "selectableInWarband": false,
            "warbandSize": 12
        }
    },
    "magic": {},
    "modelCount": 1,
    "mounts": {},
    "name": "Rúmil",
    "unique": true,
    "uniqueName": "Rúmil",
    "points": 85,
    "race": {
        "Elf": {},
        "Lόrien": {}
    },
    "rules": {
        "Woodland Creature": {
            "type": "Passive"
        },
        "Swift Parry": {
            "type": "Active"
        }
    },
    "stats": {
        "movement": 6,
        "fight": 6,
        "range": 3,
        "strength": 4,
        "defence": 7,
        "attacks": 2,
        "wounds": 2,
        "courage": 6,
        "might": {
            "current": 3
        },
        "will": {
            "current": 1
        },
        "fate": {
            "current": 1
        }
    },
    "type": {
        "Infantry": {}
    },
    "wargear": {
        "Heavy Armour": {
            "optional": false,
            "points": 0,
            "type": "Passive",
            "userSelected": false
        },
        "Elven-Made Sword": {
            "optional": false,
            "points": 0,
            "type": "Passive",
            "userSelected": false
        },
        "Shield": {
            "optional": false,
            "points": 0,
            "type": "Passive",
            "userSelected": false
        },
        "Elven Cloak": {
            "optional": true,
            "points": 5,
            "type": "Passive",
            "userSelected": false
        }
    },
    "references": {
        "books": {
            "Armies Of The Lord Of The Rings": {
                "page": 84,
                "initials": "AotLotR"
            }
        }
    },
    "version": 1.0
}

=== Oakflesh/MEAL-DATA/Model Profiles/Good/Lothlórien/Wood Elf Sentinel.json
{
    "actions": {},
    "armies": {
        "Lothlórien": {
            "tier": "Warrior",
            "selectableInWarband": true,
            "warbandSize": 0
        }
    },
    "magic": {},
    "modelCount": 1,
    "mounts": {},
    "name": "Wood Elf Sentinel",
    "unique": false,
    "points": 25,
    "race": {
        "Elf": {},
        "Lόrien": {}
    },
    "rules": {
        "Woodland Creature": {
            "type": "Passive"
        },
        "Enchanting Song": {
            "type": "Active"
        }
    },
    "stats": {
        "movement": 6,
        "fight": 5,
        "range": 3,
        "strength": 3,
        "defence": 3,
        "attacks": 2,
        "wounds": 1,
        "courage": 5
    },
    "type": {
        "Infantry": {}
    },
    "wargear": {
        "Elven-Made Sword": {
            "optional": false,
            "points": 0,
            "type": "Passive",
            "userSelected": false
        },
        "Elf Bow": {
            "optional": false,
            "points": 0,
            "type": "Passive",
            "userSelected": false
        },
        "Elven Cloak": {
            "optional": false,
            "points": 0,
            "type": "Passive",
            "userSelected": false
        }
    },
    "references": {
        "books": {
            "Armies Of The Lord Of The Rings": {
                "page": 89,
                "initials": "AotLotR"
            }
        }
    },
    "version": 1.0
}

=== Oakflesh/MEAL-DATA/Model Profiles/Forces of Good/The Shire/Lobelia Sackville-Baggins.json
{
    "actions": {},
    "armies": {
        "The Shire": {
            "tier": "Minor Hero",
            "selectableInWarband": false,
            "warbandSize": 6
        }
    },
    "magic": {},
    "modelCount": 1,
    "mounts": {},
    "name": "Lobelia Sackville-Baggins",
    "unique": true,
    "uniqueName": "Lobelia Sackville-Baggins",
    "points": 15,
    "race": {
        "Hobbit": {}
    },
    "rules": {
        "Resistant To Magic": {
            "type": "Passive"
        },
        "Throw Stones (Hobbit)": {
            "type": "Active"
        },
        "Furious Tirade": {
            "type": "Active"
        },
        "The Umbrella Is Not Mightier Than The Sword": {
            "type": "Passive"
        }
    },
    "stats": {
        "movement": 4,
        "fight": 2,
        "range": 3,
        "strength": 1,
        "defence": 2,
        "attacks": 1,
        "wounds": 1,
        "courage": 6,
        "might": {
            "current": 0
        },
        "will": {
            "current": 3
        },
        "fate": {
            "current": 1
        }
    },
    "type": {
        "Infantry": {}
    },
    "wargear": {
        "Umbrella": {
            "optional": false,
            "points": 0,
            "type": "Passive",
            "userSelected": false
        }
    },
    "references": {
        "books": {
            "Armies Of The Lord Of The Rings": {
                "page": 20,
                "initials": "AotLotR"
            }
        }
    },
    "version": 1.0
}

=== Oakflesh/MEAL-DATA/Model Profiles/Good/Rohan/Rohan Royal Guard.json
{
    "actions": {},
    "armies": {
        "Rohan": {
            "tier": "Warrior",
            "selectableInWarband": true,
            "warbandSize": 0
        }
    },
    "magic": {},
    "modelCount": 1,
    "mounts": {
        "Horse": {
            "points": 5,
            "userSelected": false
        }
    },
    "name": "Rohan Royal Guard",
    "unique": false,
    "points": 10,
    "race": {
        "Man": {},
        "Rohan": {}
    },
    "rules": {
        "Bodyguard": {
            "type": "Passive"
        },
        "Expert Rider": {
            "type": "Passive"
        },
        "Arise Riders Of Th√©oden": {
            "type": "Active"
        }
    },
    "stats": {
        "movement": 6,
        "fight": 4,
        "range": 4,
        "strength": 3,
        "defence": 6,
        "attacks": 1,
        "wounds": 1,
        "courage": 3
    },
    "type": {
        "Infantry": {}
    },
    "wargear": {
        "Heavy Armour": {
            "optional": false,
            "points": 0,
            "type": "Passive",
            "userSelected": false
        },
        "Sword": {
            "optional": false,
            "points": 0,
            "type": "Passive",
            "userSelected": false
        },
        "Shield": {
            "optional": false,
            "points": 0,
            "type": "Passive",
            "userSelected": false
        },
        "Banner": {
            "optional": true,
            "points": 25,
            "type": "Passive",
            "userSelected": false
        },
        "Throwing Spears": {
            "optional": true,
            "points": 2,
            "type": "Passive",
            "userSelected": false
        }
    },
    "references": {
        "books": {
            "Armies Of The Lord Of The Rings": {
                "page": 68,
                "initials": "AotLotR"
            }
        }
    },
    "version": 1.0
}

=== Oakflesh/MEAL-DATA/Model Profiles/Forces of Good/The Kingdom Of Khazad-Dûm/Flói Stonehand.json
{
    "actions": {
        "Strength": {}
    },
    "armies": {
        "The Kingdom Of Khazad-Dûm": {
            "tier": "Hero of Fortitude",
            "selectableInWarband": false,
            "warbandSize": 12
        }
    },
    "magic": {},
    "modelCount": 1,
    "mounts": {},
    "name": "Flói Stonehand",
    "unique": true,
    "uniqueName": "Flói Stonehand",
    "points": 75,
    "race": {
        "Dwarf": {},
        "Moria": {}
    },
    "rules": {
        "Loremaster": {
            "type": "Active"
        }
    },
    "stats": {
        "movement": 5,
        "fight": 4,
        "range": 4,
        "strength": 4,
        "defence": 6,
        "attacks": 2,
        "wounds": 2,
        "courage": 5,
        "might": {
            "current": 1
        },
        "will": {
            "current": 3
        },
        "fate": {
            "current": 1
        }
    },
    "type": {
        "Infantry": {}
    },
    "wargear": {
        "Heavy Dwarf Armour": {
            "optional": false,
            "points": 0,
            "type": "Passive",
            "userSelected": false
        },
        "Staff": {
            "optional": false,
            "points": 0,
            "type": "Active",
            "userSelected": false
        }
    },
    "references": {
        "books": {
            "Armies Of The Lord Of The Rings": {
                "page": 98,
                "initials": "AotLotR"
            }
        }
    },
    "version": 1.0
}

=== Oakflesh/MEAL-DATA/Model Profiles/Forces of Good/Minas Tirith/King Of Men.json
{
    "actions": {
        "March": {},
        "Defence": {}
    },
    "armies": {
        "Minas Tirith": {
            "tier": "Hero of Fortitude",
            "selectableInWarband": false,
            "warbandSize": 12
        }
    },
    "magic": {},
    "modelCount": 1,
    "mounts": {
        "Armoured Horse": {
            "points": 15,
            "userSelected": false
        },
        "Horse": {
            "points": 10,
            "userSelected": false
        }
    },
    "name": "King Of Men",
    "unique": false,
    "points": 60,
    "race": {
        "Man": {},
        "Gondor": {}
    },
    "rules": {},
    "stats": {
        "movement": 6,
        "fight": 5,
        "range": 4,
        "strength": 4,
        "defence": 5,
        "attacks": 2,
        "wounds": 2,
        "courage": 5,
        "might": {
            "additional": 0,
            "points": 0,
            "value": 2
        },
        "will": {
            "additional": 0,
            "points": 0,
            "value": 2
        },
        "fate": {
            "additional": 0,
            "points": 0,
            "value": 1
        }
    },
    "type": {
        "Infantry": {}
    },
    "wargear": {
        "Armour": {
            "optional": false,
            "points": 0,
            "type": "Passive",
            "userSelected": false
        },
        "Sword": {
            "optional": false,
            "points": 0,
            "type": "Passive",
            "userSelected": false
        },
        "Heavy Armour": {
            "optional": true,
            "points": 5,
            "type": "Passive",
            "userSelected": false
        },
        "Lance": {
            "optional": true,
            "points": 5,
            "type": "Passive",
            "userSelected": false
        },
        "Shield": {
            "optional": true,
            "points": 5,
            "type": "Passive",
            "userSelected": false
        }
    },
    "references": {
        "books": {
            "Armies Of The Lord Of The Rings": {
                "page": 40,
                "initials": "AotLotR"
            }
        }
    },
    "version": 1.0
}

=== Oakflesh/MEAL-DATA/Model Profiles/Forces of Good/The Fellowship/Samwise Gamgee.json
{
    "actions": {
        "Strike": {},
        "Strength": {}
    },
    "armies": {
        "The Fellowship": {
            "tier": "Hero of Fortitude",
            "selectableInWarband": false,
            "warbandSize": 0
        }
    },
    "magic": {},
    "modelCount": 1,
    "mounts": {},
    "name": "Samwise Gamgee",
    "unique": true,
    "uniqueName": "Samwise",
    "points": 40,
    "race": {
        "Hobbit": {}
    },
    "rules": {
        "Resistant To Magic": {
            "type": "Passive"
        },
        "Throw Stones (Hobbit)": {
            "type": "Active"
        },
        "Let Him Go Or I'll Have You, Longshanks!": {
            "type": "Active"
        }
    },
    "stats": {
        "movement": 4,
        "fight": 3,
        "range": 3,
        "strength": 2,
        "defence": 3,
        "attacks": 1,
        "wounds": 2,
        "courage": 6,
        "might": {
            "current": 2
        },
        "will": {
            "current": 2
        },
        "fate": {
            "current": 2
        }
    },
    "type": {
        "Infantry": {}
    },
    "wargear": {
        "Dagger": {
            "optional": false,
            "points": 0,
            "type": "Passive",
            "userSelected": false
        },
        "Elven Cloak": {
            "optional": true,
            "points": 5,
            "type": "Passive",
            "userSelected": false
        }
    },
    "references": {
        "books": {
            "Armies Of The Lord Of The Rings": {
                "page": 9,
                "initials": "AotLotR"
            }
        }
    },
    "version": 1.0
}

=== Oakflesh/MEAL-DATA/Model Profiles/Good/The Fellowship/Sméagol.json
{
    "actions": {},
    "armies": {
        "The Fellowship": {
            "tier": "Independent Hero",
            "selectableInWarband": false,
            "warbandSize": 0
        }
    },
    "magic": {},
    "modelCount": 1,
    "mounts": {},
    "name": "Sm√©agol",
    "unique": true,
    "uniqueName": "Gollum",
    "points": 30,
    "race": {
        "Hobbit": {}
    },
    "rules": {
        "Cave Dweller": {
            "type": "Passive"
        },
        "Serve The Master Of The Precious": {
            "type": "Passive"
        }
    },
    "stats": {
        "movement": 5,
        "fight": 4,
        "range": 4,
        "strength": 4,
        "defence": 4,
        "attacks": 2,
        "wounds": 2,
        "courage": 4,
        "might": {
            "additional": 0,
            "points": 0,
            "value": 1
        },
        "will": {
            "additional": 0,
            "points": 0,
            "value": 0
        },
        "fate": {
            "additional": 0,
            "points": 0,
            "value": 1
        }
    },
    "type": {
        "Infantry": {}
    },
    "wargear": {
        "Strong Strangling Fingers": {
            "optional": false,
            "points": 0,
            "type": "Passive",
            "userSelected": false
        }
    },
    "references": {
        "books": {
            "Armies Of The Lord Of The Rings": {
                "page": 15,
                "initials": "AotLotR"
            }
        }
    },
    "version": 1.0
}
